			<div id="edit_supply_window" class='overlay'>
				<div class="modal">
					<h3>Add printer</h3>
					<hr>
					<table>
						<tr>
							<td class='label'><label>Name:</label></td>
							<td class='input'><input id='edit_supply_name' type='text' /></td>
						</tr>
						<tr>
							<td class='label'><label>Model:</label></td>
							<td class='input'><input id='edit_supply_model' type='text' /></td>
						</tr>
						<tr>
							<td class='label'><label>Area:</label></td>
							<td class='input'><select id='edit_supply_area'>
									<option>Капотня
									<option>Дмитровка
									<option>Теплый Стан
								</select>
							</td>
						</tr>
						<tr>
							<td class='label'><label>Supply:</label></td>
							<td class='input'>
								<select id='edit_supply' multiple>
									<option>HP Q7553X
									<option>HP Q7553A
									<option>HP CE505X
									<option>Xerox 3550X
								</select>
							</td>
						</tr>
						<tr>
							<td class='label'><label>Comment:</label></td>
							<td class='input'><input type='text'></td>
						</tr>
					</table>
					
					<hr>
					<button class='pic red cancel modal_close'	onclick="" type='button'>Cancel</button>
					<button class='pic green save'	onclick="" type='submit'>Save</button>
				</div>
			</div>